site_name: XMS Docs
site_url: https://docs.xmsystems.co.uk/

nav:
  - Welcome: index.md
  - Overview: overview.md
  - Network: 
    - Unifi Cloud Gateway Ultra: Unifi Cloud Gateway Ultra.md
    - Unifi USW-Lite-16-PoE: Unifi USW-Lite-16-PoE.md
    - Unifi Access Points: Unifi Access Points.md
  - Servers & Devices:
    - TiTAN: titan.md
    - Phobos: phobos.md
    - Gurdy: gurdy.md
    - NCC-1702: NCC-1702.md
    - NCC-1703: NCC-1703.md
    - NCC-1704: NCC-1704.md
  - Docker: docker.md
  - Applications:
    - Traefik: traefik.md
    - Traefik - Entry Points: entrypoints.md
    - Traefik - Dynamic Files: dynamic.md
    - Nebula-Sync: nebula-sync.md
    - Plex & Overseerr: plex.md
    - Tautulli: tautulli.md
    - Navidrome: navidrome.md
    - SABnzbd: sabnzbd.md
    - Arrs: arrs.md
    - Homepage: homepage.md
    - Home Assistant: ha.md
    - Monitoring: monitoring.md
    - Portainer: portainer.md
    - Uptime-Kuma: kuma.md
    - Motioneye: motioneye.md
    - Ghost: ghost.md
  - Archive:
    - USG: USG.md
    - Duplicati: duplicati.md
    - Glances: glances.md
    - Vaultwarden: vaultwarden.md
    - Cuthbert: cuthbert.md

theme:
  logo: images/server-solid.svg
  name: 'material'
  palette:
    scheme: slate
    primary: purple
    accent: green
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.paths
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotation
    - content.code.select
    - content.tabs.link
  language: en

  icon:
    repo: fontawesome/brands/github

extra:
  consent:
    title: Cookie consent
    description: >- 
      xander's lab uses cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of the documentation and whether users
      find what they're searching for. With your consent, you're helping me
      make the documentation better.

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

repo_url: https://github.com/xanderlicious/mkdocs
repo_name: xanderlicious/mkdocs

