site_name: XM Systems
site_url: https://docs.xmsystems.co.uk/

nav:
  - Welcome: index.md
  - Overview: overview.md
  - Devices: 
    - Unifi Cloud Gateway Ultra: Unifi Cloud Gateway Ultra.md
    - Unifi USW-Lite-16-PoE: Unifi USW-Lite-16-PoE.md
    - Unifi Access Points: Unifi Access Points.md
  - Servers:
    - TiTAN: titan.md
    - Cuthbert: cuthbert.md
    - Gurdy: gurdy.md
    - NCC-1702: NCC-1702.md
    - NCC-1703: NCC-1703.md
  - Docker: docker.md
  - Applications:
    - Traefik : traefik.md
    - Traefik Entry Points: entrypoints.md
    - Traefik Dynamic Files: dynamic.md
    - Plex & Overseerr: plex.md
    - Tautulli: tautulli.md
    - Navidrome: navidrome.md
    - SABnzbd: sabnzbd.md
    - Arrs: arrs.md
    - Homepage: homepage.md
    - Home Assistant: ha.md
    - Monitoring: monitoring.md
    - Portainer: portainer.md
    - Vaultwarden: vaultwarden.md
    - Uptime-Kuma: kuma.md
    - Motioneye: motioneye.md
  - Archive:
    - USG: USG.md
    - Duplicati: duplicati.md
    - Glances: glances.md


theme:
  logo: images/server-solid.svg
  name: 'material'
  palette:
    scheme: slate
    primary: purple
    accent: teal
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotation
    - content.code.select
    - content.tabs.link
  language: en
  icon:
    repo: fontawesome/brands/git-alt

extra:
  consent:
    title: Cookie consent
    description: >- 
      xander's lab uses cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of the documentation and whether users
      find what they're searching for. With your consent, you're helping me
      make the documentation better.

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

repo_url: https://github.com/xanderlicious/mkdocs
repo_name: xanderlicious/mkdocs

