site_name: XMS Docs
site_url: https://docs.xmsystems.co.uk/

nav:
  - Welcome: index.md
  - Overview: overview.md
  - Network: 
    - Unifi Cloud Gateway Ultra: Unifi Cloud Gateway Ultra.md
    - Unifi USW-Lite-16-PoE: Unifi USW-Lite-16-PoE.md
    - Unifi Access Points: Unifi Access Points.md
  - Servers & Devices:
    - Titan: titan.md
    - Phobos: phobos.md
    - Tethys: tethys.md
    - NCC-1702: NCC-1702.md
    - NCC-1703: NCC-1703.md
  - Docker:
    - Install, Config & Usage: docker.md
    - Daemon Security (mTLS): mTLS.md
    - Health Checks: healthchecks.md
  - Applications:
    - Traefik: traefik.md
    - Traefik - Entry Points: entrypoints.md
    - Traefik - Dynamic Files: dynamic.md
    - Portainer: portainer.md
    - NCC-1704: NCC-1704.md
    - Plex: plex.md
    - Navidrome: navidrome.md
    - Podgrab: podgrab.md
    - Seerr: seerr.md
    - Tautulli: tautulli.md
    - Arrs: arrs.md
    - SABnzbd: sabnzbd.md
    - IT-Tools: it-tools.md
    - Homepage: homepage.md
    - Home Assistant: ha.md
    - Motioneye: motioneye.md
    - MySQL Database: mysql.md
    - phpMyAdmin: phpmyadmin.md
    - Nginx Web Server: nginx.md
    - Ghost: ghost.md
    - PH-Intercept: ph-intercept.md
    - Apache Guacamole: guacamole.md
    - Fail2Ban: fail2ban.md
    - Nebula-Sync: nebula-sync.md
  - Monitoring, Alerting & Logging:
    - Grafana / Prometheus: grafana & prometheus.md
    - Exporters & Scrapers: exporters.md
    - CheckMK: checkmk.md
    - Uptime-Kuma: kuma.md
    - Dozzle: dozzle.md
  - Archive:
    - USG: USG.md
    - Duplicati: duplicati.md
    - Glances: glances.md
    - Vaultwarden: vaultwarden.md
    - Cuthbert: cuthbert.md

theme:
  logo: images/server-solid.svg
  name: 'material'
  palette:
    scheme: slate
    primary: purple
    accent: green
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    #- navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotation
    - content.code.select
    - content.tabs.link
  language: en

  icon:
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: google
    property: G-3XSJT56P7R
  consent:
    title: Cookie consent
    description: >- 
      xander's lab uses cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of the documentation and whether users
      find what they're searching for. With your consent, you're helping me
      make the documentation better.

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:

repo_url: https://github.com/xanderlicious/mkdocs
repo_name: xanderlicious/mkdocs
